- name: Disable systemd-resolved DNSStubListener
  ansible.builtin.shell: |
    printf "%b  %b Disabling systemd-resolved DNSStubListener" "${OVER}" "${TICK}"
    sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
    systemctl reload-or-restart systemd-resolved
  become: yes

- name: Ensure {{ pihole_dir }} directory exists
  become: yes
  ansible.builtin.file:
    path: '{{ pihole_dir }}'
    state: directory

- name: Copy Pihole Config
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  become: yes
  loop:
    - { src: '{{ role_path }}/templates/compose.yaml.j2', dest: '{{ pihole_dir }}/compose.yaml' }
    - { src: '{{ role_path }}/templates/pihole.toml.j2', dest: '{{ pihole_dir }}/pihole.toml' }

- name: Tear down existing services
  become: yes
  community.docker.docker_compose_v2:
    project_src: '{{ pihole_dir }}'
    state: absent
    remove_orphans: true

- name: Ensure pihole and update is up and running
  become: yes
  community.docker.docker_compose_v2:
    project_src: '{{ pihole_dir }}'
  register: output
  environment:
    PI_HOLE_ADMIN_PASSWORD: '{{ lookup("env", "PI_HOLE_ADMIN_PASSWORD") }}'

- name: Show compose output
  ansible.builtin.debug:
    var: output
