- name: Disable systemd-resolved DNSStubListener
  ansible.builtin.shell: |
    printf "%b  %b Disabling systemd-resolved DNSStubListener" "${OVER}" "${TICK}"
    sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
    systemctl reload-or-restart systemd-resolved
  become: yes

- name: Ensure pihole and update is up and running
  ansible.builtin.shell:
  become: yes
  args:
    chdir: "~/ansible-collections/homelab/roles/pihole/files"
    cmd: |
      docker compose down
      docker compose up -d

- name: Docker compose ps
  ansible.builtin.shell:
  become: yes
  args:
    chdir: "~/ansible-collections/homelab/roles/pihole/files"
    cmd: docker compose ps
  register: docker_compose_ps_output

- name: Show docker compose ps output
  ansible.builtin.debug:
    var: docker_compose_ps_output.stdout
