# Arch Linux specific variables

# Authentication settings
ansible_user: '{{ lookup("env", "HOMELAB_USER") | default("admin") }}'
ansible_become_method: sudo

# SSH settings
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Arch-specific overrides
install_dev_tools: true
install_multimedia: true
install_gaming: false
update_mirrors: true

# Custom package lists for Arch systems
arch_essential_packages:
  - base-devel
  - git
  - curl
  - wget
  - vim
  - htop
  - tree
  - unzip
  - zip
  - rsync
  - openssh
  - sudo
  - which
  - man-db
  - man-pages
