# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(md|rst)$'
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--call-module-type=local
          - --args=--recursive
          - --args=--format=compact

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        additional_dependencies: ["gibberish-detector"]
        exclude: package.lock.json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.20
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: local
    hooks:
      - name: type-check
        id: type-check
        entry: zsh -c 'uv run ty check'
        language: system
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: "Checks the style of Markdown/CommonMark files."
        entry: uv run markdownlint-cli2 **/*.md
        language: node
        types: [markdown]
