[project]
name = "ansible-collections"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.7.0",
    "proxmoxer>=2.2.0",
    "ruff>=0.12.3",
    "ty>=0.0.1a14",
    "typer>=0.16.0",
]
