dependencies:
  - role: geerlingguy.pip
    vars:
      pip_install_packages:
        - name: docker
    when: initialization == true | default(false)

  - role: geerlingguy.docker
    vars:
      docker_users:
        - "{{ ansible_user }}"
    when: initialization == true | default(false)
