---
- name: Deploy Gitea Actions Runner
  hosts: lxc_containers
  become: false # Already running as root in LXC
  gather_facts: true
  vars:
    domain: '{{ lookup("env", "HOMELAB_DOMAIN_PROD") }}'

  roles:
    - role: gitea-runner
      vars:
        # Use binary installation for LXC containers but with Docker for job execution
        gitea_runner_install_method: "binary"
        gitea_runner_use_docker_for_jobs: true
        gitea_runner_become: false # Already running as root        uvr ansible-playbook playbooks/prod/gitea.runner.yaml
        gitea_runner_name: "lxc-{{ inventory_hostname }}"
        gitea_runner_labels: "ubuntu-latest:docker://catthehacker/ubuntu:act-latest,self-hosted:docker,linux:docker,lxc:docker"
        gitea_runner_log_level: "info"
        registration_token: '{{ lookup("env", "GITEA_RUNNER_REGISTRATION_TOKEN_PROD1") }}'
        gitea_runner_force_registration: true
        domain: '{{ lookup("env", "HOMELAB_DOMAIN_PROD") }}'
        gitea_runner_docker_network: "bridge"
        gitea_runner_docker_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        initialization: true
