---
# Simple test playbook for NFS client role
# This will set up dns-prod as an NFS client to connect to pve-prod1 NFS server

- name: Test NFS Client Setup
  hosts: nfs_clients
  become: true
  gather_facts: true

  vars:
    # Simple NFS mount configuration for testing
    nfs_mounts:
      - server: "192.168.10.10" # pve-prod1
        path: "/mnt/pve/backups/vms"
        mount_point: "/mnt/nfs-1t"
        fstype: "nfs4"
        options: "defaults,nfsvers=4,rsize=8192,wsize=8192,timeo=14,soft"
        state: "mounted"
        persistent: true
        owner: root
        group: root
        mode: "0755"

    # Client configuration
    nfs_client_domain: "{{ lookup('env', 'HOMELAB_DOMAIN_PROD') | default('home.mombesoft.com') }}"
    nfs_validate_mounts: true

  roles:
    - nfs-client

  post_tasks:
    - name: Test NFS mount access
      ansible.builtin.command: ls -la /mnt/nfs-1t
      register: nfs_test_result
      changed_when: false
      failed_when: false

    - name: Display test results
      ansible.builtin.debug:
        msg: "NFS mount test result: {{ 'SUCCESS' if nfs_test_result.rc == 0 else 'FAILED' }}"

    - name: Show mount details
      ansible.builtin.debug:
        var: nfs_test_result.stdout_lines
      when: nfs_test_result.rc == 0
