---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_os_family == "Debian"

- name: Install required packages for Netbird repository
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Download and add Netbird GPG key
  ansible.builtin.get_url:
    url: https://pkgs.netbird.io/debian/public.key
    dest: /tmp/netbird-public.key
    mode: "0644"
  become: true
  when: ansible_os_family == "Debian"

- name: Import Netbird GPG key
  ansible.builtin.shell:
    cmd: gpg --dearmor --output /usr/share/keyrings/netbird-archive-keyring.gpg /tmp/netbird-public.key
    creates: /usr/share/keyrings/netbird-archive-keyring.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Add Netbird repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main"
    filename: netbird
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Clean up temporary GPG key file
  ansible.builtin.file:
    path: /tmp/netbird-public.key
    state: absent
  become: true
  when: ansible_os_family == "Debian"

- name: Update apt package cache after adding Netbird repository
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install Netbird
  ansible.builtin.apt:
    name: netbird
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Start Netbird For the first time
  ansible.builtin.shell:
    cmd: netbird up --setup-key {{netbird_auth_token}}
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure Netbird service is enabled and started
  ansible.builtin.systemd:
    name: netbird
    enabled: true
    state: started
  become: true
  when: ansible_os_family == "Debian"
