namespace: "namespace_name"
name: "homelab-utilities"
version: "1.0.12"
readme: "README.md"
authors:
  - "mombe090"
dependencies:
  "other_namespace.collection1": ">=1.0.0"
  "other_namespace.collection2": ">=2.0.0,<3.0.0"
  "anderson55.my_collection": "*"    # note: "*" selects the highest version available
license:
  - "MIT"
tags:
  - demo
  - collection
repository: "https://www.github.com/mombe090/ansible-collections"