---
# External Ansible Galaxy roles required by this collection
roles:
  - name: geerlingguy.pip
    version: "3.1.0"
  - name: geerlingguy.docker
    version: "7.4.1"

# External collections (if needed)
collections:
  - name: community.general
    version: ">=5.0.0"
  - name: community.docker
    version: ">=3.0.0"
