- name: Make sure docker is running
  ansible.builtin.systemd_service:
    name: docker
    state: started

- name: Ensure all required folders are created
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - '{{ traefik_dir }}/config'
    - '{{ traefik_dir }}/config/conf.d'
    - '{{ traefik_dir }}/data/certs/'

- name: Copy Traefik config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: yes
  loop:
    - { src: '{{ role_path }}/templates/traefik.external.yaml.j2', dest: '{{ traefik_dir }}/config/conf.d/external-services.yml' }
    - { src: '{{ role_path }}/templates/traefik.config.yaml.j2', dest: '{{ traefik_dir }}/config/traefik.yml' }
    - { src: '{{ role_path }}/templates/authentik.config.yaml.j2', dest: '{{ traefik_dir }}/config/conf.d/authentik.middleware.yml' }

- name: Ensure traefik is up and running
  ansible.builtin.shell:
  become: yes
  args:
    chdir: "~/ansible-collections/homelab/roles/pihole/files"
    cmd: |
      docker compose down
      docker compose up -d
  become_user: "{{ ansible_user }}"

- name: Docker compose ps
  ansible.builtin.shell:
  become: yes
  args:
    chdir: "~/ansible-collections/homelab/roles/pihole/files"
    cmd: docker compose ps
  register: docker_compose_ps_output
  become_user: "{{ ansible_user }}"

- name: Show docker compose ps output
  ansible.builtin.debug:
    var: docker_compose_ps_output.stdout
  become_user: "{{ ansible_user }}"
