- name: Make sure docker is running
  ansible.builtin.systemd_service:
    name: docker
    state: started

- name: Ensure all required folders are created
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - '{{ traefik_dir }}/config'
    - '{{ traefik_dir }}/config/conf.d'
    - '{{ traefik_dir }}/data/certs/'

- name: Copy Traefik config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: yes
  loop:
    - { src: '{{ role_path }}/templates/traefik.external.yaml.j2', dest: '{{ traefik_dir }}/config/conf.d/external-services.yml' }
    - { src: '{{ role_path }}/templates/traefik.config.yaml.j2', dest: '{{ traefik_dir }}/config/traefik.yml' }
    - { src: '{{ role_path }}/templates/authentik.config.yaml.j2', dest: '{{ traefik_dir }}/config/conf.d/authentik.middleware.yml' }

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "~/ansible-collections/homelab/roles/traefik/files"
    state: absent
