- name: Ensure all required folders are created
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ traefik_dir }}/config"
    - "{{ traefik_dir }}/config/conf.d"
    - "{{ traefik_dir }}/data/certs/"
    - "{{ traefik_dir }}/composes"

- name: Make sure docker is running
  ansible.builtin.systemd_service:
    name: docker
    state: started

- name: Ensure proxy docker network exists
  docker_network:
    name: proxy
    state: present

- name: Import Traefik Server Task
  ansible.builtin.include_tasks: traefik_server.yaml
