- name: Check if Homebrew is already installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  become_user: "{{ ansible_user }}"
  register: brew_installed

- name: Install Homebrew if not already installed
  ansible.builtin.shell: |
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  become_user: "{{ ansible_user }}"
  when: not brew_installed.stat.exists

- name: Ensure .zshrc exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.zshrc"
    state: touch
  become_user: "{{ ansible_user }}"

- name: Add Homebrew to PATH for zsh user
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present
  become_user: "{{ ansible_user }}"

- name: Verify Homebrew installation
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/brew --version
  register: brew_version
  changed_when: false

- name: Display Homebrew version
  ansible.builtin.debug:
    msg: "Homebrew version: {{ brew_version.stdout }}"
