- name: Install Development tools on Redhat family
  become: yes
  ansible.builtin.dnf:
    name: "@Development Tools"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install linux essentials on Debian family
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      #- eza
      - fzf
      - gnupg
      - jq
      - python3
      - python3-pip
      - neovim
      - nmap
      - nfs-common
      - prometheus-node-exporter
      - qemu-guest-agent
      - tmux
      - unzip
      - vim
      #- yq
      - xz-utils
      - zoxide
      - zip
      - zsh
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Download EPEL Fedora release package
  ansible.builtin.shell:
    cmd: curl -O https://dl.fedoraproject.org/pub/epel/9/Everything/aarch64/Packages/e/epel-release-9-9.el9.noarch.rpm
  when: ansible_os_family == 'RedHat'

- name: Install EPEL release package
  become: yes
  ansible.builtin.dnf:
    name: epel-release-9-9.el9.noarch.rpm
    state: present
    disable_gpg_check: true
  when: ansible_os_family == 'RedHat'

- name: Install linux essentials on Redhat family
  become: yes
  ansible.builtin.dnf:
    name:
      - git
      - util-linux-user
      - ca-certificates
      - curl
      - cryptsetup
      - dnf-utils
      #- eza
      - fzf
      - python3
      - python3-pip
      #- eza
      - gnupg
      - jq
      - neovim
      - nmap
      - nfs-utils
      #- prometheus-node-exporter
      - python3.12
      - qemu-guest-agent
      - iscsi-initiator-utils
      - tmux
      - unzip
      - vim
      #- yq
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - yum-utils
      - xz
      - zoxide
      - zip
      - zsh
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: Check if Go-Task is installed
  ansible.builtin.command: "task --version"
  register: task_version
  ignore_errors: true
  changed_when: false

- name: Install go-task
  become: yes
  ansible.builtin.shell:
    cmd: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
  when: task_version.failed

- name: Install guest qemu-guest-agent
  become: yes
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install guest qemu-guest-agent
  become: yes
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: start guest qemu-guest-agent
  become: yes
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: yes







