- name: Clone gitlab repo
  ansible.builtin.git:
    repo: 'ssh://git@git.home.mombesoft.com:2222/{{ ansible_user }}/{{ item }}.git'
    version: 'develop'
    accept_hostkey: true
    dest: '~/{{ item }}'
    force: true
  loop: '{{ projects }}'