- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
  become: true
  become_user: "{{ ansible_user }}"

- name: Generate SSH Keys for User
  ansible.builtin.openssh_keypair:
    state: present
    path: "~/.ssh/id_ed25519"
    type: ed25519
    size: 4096
    comment: "{{ ansible_user }}@{{ ansible_hostname }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  become_user: "{{ ansible_user }}"

- name: Generate Git Configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "~/.gitconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become_user: "{{ ansible_user }}"

- name: Set Github Token
  ansible.builtin.set_fact:
    github_token: "{{ lookup('env', 'HOMELAB_GITHUB_TOKEN') }}"
  become_user: "{{ ansible_user }}"

- name: Clone Ansible Collections Repo
  ansible.builtin.git:
    repo: https://{{ ansible_user }}:{{ github_token }}@github.com/{{ lookup('env', 'HOMELAB_USER') }}/ansible-collections.git
    version: main
    dest: "~/ansible-collections"
    force: true
  become_user: "{{ ansible_user }}"
  timeout: 10

- name: Clone Dotfiles Repo
  ansible.builtin.git:
    repo: https://{{ ansible_user }}:{{ github_token }}@github.com/{{ lookup('env', 'HOMELAB_USER') }}/dotfiles.git
    version: main
    dest: "~/dotfiles"
    force: true
  become_user: "{{ ansible_user }}"
  timeout: 10
