- ansible.builtin.include_tasks: qeumu_ga.yaml
  when: virtualization_type == "kvm" and initialization == true | default(false)

- name: Ensure .zshrc exists
  ansible.builtin.file:
    path: "~/.zshrc"
    state: touch
  become_user: "{{ ansible_user }}"

- ansible.builtin.include_tasks: base_packages.yaml
  when: initialization == true | default(false)

#- ansible.builtin.include_tasks: brew_packages.yaml
#  when: install_brew == true and initialization == true

- ansible.builtin.include_tasks: git_setup.yaml
  when: initialization == true | default(false)

- ansible.builtin.include_tasks: zsh_config.yaml
  when: initialization == true | default(false)

- name: Copy Role files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: /tmp
    mode: "0777"
  become: true
  when: install_brew == true and ansible_user != "root" and initialization == true

- ansible.builtin.include_tasks: brew_packages.yaml
  when: install_brew == true and ansible_user != "root" and initialization == true

- name: Install Homebrew Packages
  become: true
  ansible.builtin.shell:
    cmd: |
      chmod +x /tmp/brew-packages.sh
      /bin/bash /tmp/brew-packages.sh
  become_user: "{{ ansible_user }}"
  when: install_brew == true and ansible_user != "root" and initialization == true

- name: Install go-task
  become: true
  ansible.builtin.shell:
    cmd: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    creates: /usr/local/bin/task
  when: install_dev_tools == true
