- name: Stow Dotfiles
  ansible.builtin.command:
    cmd: stow .
  args:
    chdir: "/home/{{ ansible_user }}/dotfiles"
  become_user: "{{ ansible_user }}"

- name: Ensure Homebrew is in PATH for zsh
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present
  become_user: "{{ ansible_user }}"

- name: Ensure Import .zshrc_user file is imported in .zshrc file
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    line: "[[ -f ~/.zshrc_user ]] && source ~/.zshrc_user"
    state: present
  become_user: "{{ ansible_user }}"

- name: Change user's default shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true

- name: Install Starship
  ansible.builtin.include_tasks: starship.yaml
  when: install_starship == true | default(true)
