---
traefik_dir: /etc/traefik
services: []
cloudflare_email: 'yayamombeya090@gmail.com'
cloudflare_api_key: '{{ lookup("env", "CLOUD_FLARE_HOME_API_TOKEN") }}'
traefik_dashboard_credentials: "{{ lookup('env', 'TRAEFIK_DASHBOARD_CREDENTIALS') }}"
