dependencies:
  - role: "common"
  - role: "geerlingguy.pip"
    vars:
      pip_install_packages:
        - name: docker
  - role: "geerlingguy.docker"
    vars:
      docker_users:
        - '{{ ansible_user }}'
