dependencies:
  - role: "common"
    vars:
      install_brew: true
      install_starship: true
      install_dev_tools: false

  - role: "geerlingguy.pip"
    vars:
      pip_install_packages:
        - name: docker
  - role: "geerlingguy.docker"
    vars:
      docker_users:
        - "{{ ansible_user }}"
