node_name: pve2
api_host: 192.168.10.253
api_user: root@pam
api_password: "{{ lookup('env', 'PROXMOX_VE_PASSWORD') }}"

vmid: 0
hostname: test-lxc
os_type: ubuntu
root_password: "{{ lookup('env', 'PROXMOX_VE_PASSWORD') }}"
pub_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
template_datastore: local
os_template: ubuntu-24.04-standard_24.04-1_amd64.tar.zst
onboot: true
cores: 2
memory: 2048
disk_size: 10
disk_storage: local-lvm
nameserver: ''
searchdomain: ''
ip_address: ''
gateway: '192.168.10.1'
netmask: '24'
bridge: vmbr0
