---
galaxy_info:
  author: homelab
  description: Ansible role to setup Gitea Actions runner with Docker or binary installation
  company: homelab

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9

  galaxy_tags:
    - gitea
    - actions
    - runner
    - ci
    - cd
    - docker
    - lxc
    - automation

dependencies:
  - role: docker
    vars:
      initialization: true
    when: gitea_runner_install_method == 'binary' and gitea_runner_use_docker_for_jobs | default(true)

collections:
  - community.docker # Required for Docker installation method
