---
# Production-specific variables for Vaultwarden
# These override the defaults for production environments

vaultwarden_version: "1.34.3"

# Security hardening for production
vaultwarden_signups_allowed: false
vaultwarden_invitations_allowed: true
vaultwarden_emergency_access_allowed: true

# Enhanced backup configuration for production
vaultwarden_backup_enabled: true
vaultwarden_backup_retention_days: 90
vaultwarden_backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Production labels with additional security headers
vaultwarden_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.{{ domain }}`)"
  - "traefik.http.routers.vaultwarden.entrypoints=https"
  - "traefik.http.routers.vaultwarden.tls=true"
  - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
  # Security headers
  - "traefik.http.routers.vaultwarden.middlewares=security-headers@file"
  # WebSocket support
  - "traefik.http.routers.vaultwarden-ws.rule=Host(`vaultwarden.{{ domain }}`) && Path(`/notifications/hub`)"
  - "traefik.http.routers.vaultwarden-ws.entrypoints=https"
  - "traefik.http.routers.vaultwarden-ws.tls=true"
  - "traefik.http.routers.vaultwarden-ws.service=vaultwarden-ws"
  - "traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012"
