---
galaxy_info:
  author: homelab
  description: Deploy Vaultwarden password manager with Docker Compose
  company: homelab
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - vaultwarden
    - bitwarden
    - password
    - manager
    - docker
    - compose
    - security

dependencies:
  - role: docker
    vars:
      initialization: false
    when: docker_install | default(true)

collections:
  - community.docker
  - ansible.posix
